<?php
defined('ABSPATH') || exit;
final class MUTQAN_Settlements {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_settlements';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,user_id bigint unsigned NOT NULL,period_from date NOT NULL,period_to date NOT NULL,commissions decimal(14,2) NOT NULL DEFAULT 0,advances decimal(14,2) NOT NULL DEFAULT 0,expenses decimal(14,2) NOT NULL DEFAULT 0,net_amount decimal(14,2) NOT NULL DEFAULT 0,status varchar(30) NOT NULL DEFAULT 'draft',created_at datetime NOT NULL,paid_at datetime NULL,PRIMARY KEY(id),KEY user_id(user_id),KEY status(status)) $c;");}
 private static function manage(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');}
 public static function rest(){register_rest_route('mutqan/v1','/settlements',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$uid=absint($p['user_id']??0);$from=sanitize_text_field($p['period_from']??gmdate('Y-m-01'));$to=sanitize_text_field($p['period_to']??gmdate('Y-m-d'));$comm=(float)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(commission_amount),0) FROM ".MUTQAN_Commissions::ledger()." WHERE user_id=%d AND created_at BETWEEN %s AND %s",$uid,$from.' 00:00:00',$to.' 23:59:59'));$adv=(float)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(remaining),0) FROM ".MUTQAN_Advances::table()." WHERE user_id=%d AND created_at BETWEEN %s AND %s",$uid,$from.' 00:00:00',$to.' 23:59:59'));$net=$comm-$adv;$d=array('user_id'=>$uid,'period_from'=>$from,'period_to'=>$to,'commissions'=>$comm,'advances'=>$adv,'expenses'=>0,'net_amount'=>$net,'status'=>'draft','created_at'=>current_time('mysql',true));$wpdb->insert(self::table(),$d);$id=(int)$wpdb->insert_id;MUTQAN_Audit::log('settlement_created','settlement',$id,array('user_id'=>$uid,'net'=>$net));return rest_ensure_response(array('id'=>$id)+$d);}));register_rest_route('mutqan/v1','/settlements/(?P<id>\d+)/pay',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$x=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE id=%d",$id),ARRAY_A);if(!$x)return new WP_Error('not_found','Settlement not found.',array('status'=>404));$wpdb->update(self::table(),array('status'=>'paid','paid_at'=>current_time('mysql',true)),array('id'=>$id));MUTQAN_Audit::log('settlement_paid','settlement',$id,array('net'=>$x['net_amount']));return rest_ensure_response(array('id'=>$id,'status'=>'paid','net_amount'=>$x['net_amount']));}));}
}
MUTQAN_Settlements::init();