<?php
defined('ABSPATH') || exit;
final class MUTQAN_Wallets {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_wallets';}
 public static function tx_table(){global $wpdb;return $wpdb->prefix.'mutqan_wallet_transactions';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,user_id bigint unsigned NOT NULL,balance decimal(14,2) NOT NULL DEFAULT 0,currency varchar(8) NOT NULL DEFAULT 'SAR',status varchar(20) NOT NULL DEFAULT 'active',created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY user_id(user_id)) $c;");dbDelta("CREATE TABLE ".self::tx_table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,wallet_id bigint unsigned NOT NULL,user_id bigint unsigned NOT NULL,type varchar(40) NOT NULL,amount decimal(14,2) NOT NULL,reference_type varchar(40) NOT NULL DEFAULT '',reference_id bigint unsigned NOT NULL DEFAULT 0,status varchar(30) NOT NULL DEFAULT 'posted',note text NULL,created_at datetime NOT NULL,PRIMARY KEY(id),KEY wallet_id(wallet_id),KEY user_id(user_id),KEY reference(reference_type,reference_id)) $c;");}
 public static function ensure($uid){global $wpdb;$id=$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::table()." WHERE user_id=%d",$uid));if($id)return (int)$id;$wpdb->insert(self::table(),array('user_id'=>(int)$uid,'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true)));return (int)$wpdb->insert_id;}
 public static function post($uid,$amount,$type,$ref_type='',$ref_id=0,$note=''){global $wpdb;$wid=self::ensure($uid);if($ref_type&&$ref_id){$already=$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::tx_table()." WHERE user_id=%d AND type=%s AND reference_type=%s AND reference_id=%d AND status='posted' LIMIT 1",$uid,sanitize_key($type),sanitize_key($ref_type),(int)$ref_id));if($already)return new WP_Error('duplicate_wallet_transaction','This wallet transaction already exists.',array('status'=>409));}$w=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE id=%d FOR UPDATE",$wid),ARRAY_A);$amount=(float)$amount;if(!$w)return new WP_Error('wallet_not_found','Wallet not found.');$new=(float)$w['balance']+$amount;if($new<0)return new WP_Error('insufficient_balance','Insufficient wallet balance.',array('status'=>400));$wpdb->update(self::table(),array('balance'=>$new,'updated_at'=>current_time('mysql',true)),array('id'=>$wid));$wpdb->insert(self::tx_table(),array('wallet_id'=>$wid,'user_id'=>$uid,'type'=>sanitize_key($type),'amount'=>$amount,'reference_type'=>sanitize_key($ref_type),'reference_id'=>(int)$ref_id,'status'=>'posted','note'=>sanitize_textarea_field($note),'created_at'=>current_time('mysql',true)));MUTQAN_Audit::log('wallet_transaction','wallet',$wid,array('user_id'=>$uid,'amount'=>$amount,'type'=>$type,'reference_id'=>$ref_id));return array('wallet_id'=>$wid,'balance'=>$new);}
 private static function manage(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');}
 public static function rest(){register_rest_route('mutqan/v1','/wallets/me',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function(){return is_user_logged_in();},'callback'=>function(){$w=self::ensure(get_current_user_id());global $wpdb;return rest_ensure_response($wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE id=%d",$w),ARRAY_A));}));register_rest_route('mutqan/v1','/wallets/(?P<user_id>\d+)/topup',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){$uid=(int)$r['user_id'];$amount=(float)($r->get_json_params()['amount']??0);if($amount<=0)return new WP_Error('invalid_amount','Amount must be positive.',array('status'=>400));return rest_ensure_response(self::post($uid,$amount,'topup','','','Admin top-up'));}));register_rest_route('mutqan/v1','/wallets/(?P<user_id>\d+)/transactions',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function($r){return self::manage()||((int)$r['user_id']===get_current_user_id());},'callback'=>function($r){global $wpdb;return rest_ensure_response($wpdb->get_results($wpdb->prepare("SELECT * FROM ".self::tx_table()." WHERE user_id=%d ORDER BY id DESC LIMIT 200",(int)$r['user_id']),ARRAY_A));}));}
}
MUTQAN_Wallets::init();