<?php
defined('ABSPATH') || exit;
final class MUTQAN_Expenses {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_expenses';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,user_id bigint unsigned NOT NULL DEFAULT 0,category varchar(80) NOT NULL,amount decimal(14,2) NOT NULL,currency varchar(8) NOT NULL DEFAULT 'SAR',status varchar(30) NOT NULL DEFAULT 'pending',description text NULL,attachment_id bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,approved_at datetime NULL,PRIMARY KEY(id),KEY category(category),KEY status(status)) $c;");}
 private static function manage(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');}
 public static function rest(){register_rest_route('mutqan/v1','/expenses',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function(){global $wpdb;return rest_ensure_response($wpdb->get_results("SELECT * FROM ".self::table()." ORDER BY id DESC LIMIT 500",ARRAY_A));}));register_rest_route('mutqan/v1','/expenses',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$a=max(0,(float)($p['amount']??0));if($a<=0)return new WP_Error('invalid_expense','Amount must be positive.',array('status'=>400));$d=array('user_id'=>absint($p['user_id']??0),'category'=>sanitize_text_field($p['category']??'general'),'amount'=>$a,'currency'=>sanitize_text_field($p['currency']??'SAR'),'status'=>'pending','description'=>sanitize_textarea_field($p['description']??''),'attachment_id'=>absint($p['attachment_id']??0),'created_at'=>current_time('mysql',true));$wpdb->insert(self::table(),$d);$id=(int)$wpdb->insert_id;MUTQAN_Audit::log('expense_created','expense',$id,array('amount'=>$a));return rest_ensure_response(array('id'=>$id)+$d);}});register_rest_route('mutqan/v1','/expenses/(?P<id>\d+)/approve',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$x=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE id=%d",$id),ARRAY_A);if(!$x||$x['status']!=='pending')return new WP_Error('invalid_expense','Invalid expense.',array('status'=>400));$wpdb->update(self::table(),array('status'=>'approved','approved_at'=>current_time('mysql',true)),array('id'=>$id));MUTQAN_Audit::log('expense_approved','expense',$id,array('amount'=>$x['amount']));return rest_ensure_response(array('id'=>$id,'status'=>'approved'));}));}
}
MUTQAN_Expenses::init();