<?php
defined('ABSPATH') || exit;
final class MUTQAN_Billing {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_invoices';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, order_id bigint(20) unsigned NOT NULL, customer_id bigint(20) unsigned NOT NULL, subtotal decimal(12,2) NOT NULL DEFAULT 0, discount decimal(12,2) NOT NULL DEFAULT 0, tax decimal(12,2) NOT NULL DEFAULT 0, total decimal(12,2) NOT NULL DEFAULT 0, status varchar(30) NOT NULL DEFAULT 'draft', payment_status varchar(30) NOT NULL DEFAULT 'unpaid', currency varchar(10) NOT NULL DEFAULT 'SAR', notes text NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY(id),KEY order_id(order_id),KEY customer_id(customer_id)) $c;");}
 private static function can_manage(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_invoices')||current_user_can('mutqan_edit_orders');}
 public static function rest(){
  register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/invoice',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function($r){return MUTQAN_Orders::can_view((int)$r['id']);},'callback'=>function($r){global $wpdb;$x=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE order_id=%d",(int)$r['id']),ARRAY_A);return rest_ensure_response($x?:array('order_id'=>(int)$r['id'],'status'=>'draft','payment_status'=>'unpaid','total'=>0,'currency'=>'SAR'));}));
  register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/invoice',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function(){return self::can_manage();},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$o=$wpdb->get_row($wpdb->prepare("SELECT customer_id FROM ".MUTQAN_Orders::table()." WHERE id=%d",$id),ARRAY_A);if(!$o)return new WP_Error('not_found','Order not found.',array('status'=>404));$p=$r->get_json_params();$sub=max(0,(float)($p['subtotal']??0));$disc=max(0,(float)($p['discount']??0));$tax=max(0,(float)($p['tax']??0));$total=max(0,$sub-$disc+$tax);$d=array('order_id'=>$id,'customer_id'=>(int)$o['customer_id'],'subtotal'=>$sub,'discount'=>$disc,'tax'=>$tax,'total'=>$total,'status'=>sanitize_key($p['status']??'issued'),'payment_status'=>sanitize_key($p['payment_status']??'unpaid'),'currency'=>sanitize_text_field($p['currency']??'SAR'),'notes'=>sanitize_textarea_field($p['notes']??''),'updated_at'=>current_time('mysql',true));$old=$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::table()." WHERE order_id=%d",$id));if($old)$wpdb->update(self::table(),$d,array('id'=>(int)$old));else{$d['created_at']=current_time('mysql',true);$wpdb->insert(self::table(),$d);}MUTQAN_Audit::log('invoice_saved','order',$id,array('total'=>$total));return rest_ensure_response(array('order_id'=>$id,'total'=>$total,'currency'=>$d['currency'],'payment_status'=>$d['payment_status']));}));
  register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/payment-status',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function(){return self::can_manage();},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$s=sanitize_key(($r->get_json_params()['payment_status']??'unpaid'));if(!in_array($s,array('unpaid','pending','paid','refunded','failed'),true))return new WP_Error('invalid_payment_status','Invalid payment status.',array('status'=>400));$wpdb->update(self::table(),array('payment_status'=>$s,'updated_at'=>current_time('mysql',true)),array('order_id'=>$id));MUTQAN_Audit::log('payment_status_changed','order',$id,array('payment_status'=>$s));return rest_ensure_response(array('order_id'=>$id,'payment_status'=>$s));}));
 }
}
MUTQAN_Billing::init();
