<?php
defined('ABSPATH') || exit;
final class MUTQAN_Advances {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_advances';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,user_id bigint unsigned NOT NULL,amount decimal(14,2) NOT NULL,remaining decimal(14,2) NOT NULL,status varchar(30) NOT NULL DEFAULT 'open',note text NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),KEY user_id(user_id),KEY status(status)) $c;");}
 private static function manage(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');}
 public static function rest(){register_rest_route('mutqan/v1','/advances',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$uid=absint($p['user_id']??0);$a=max(0,(float)($p['amount']??0));if(!$uid||$a<=0)return new WP_Error('invalid_advance','User and positive amount required.',array('status'=>400));$d=array('user_id'=>$uid,'amount'=>$a,'remaining'=>$a,'status'=>'open','note'=>sanitize_textarea_field($p['note']??''),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true));$wpdb->insert(self::table(),$d);$id=(int)$wpdb->insert_id;MUTQAN_Audit::log('advance_created','advance',$id,array('user_id'=>$uid,'amount'=>$a));return rest_ensure_response(array('id'=>$id)+$d);}));register_rest_route('mutqan/v1','/advances/(?P<id>\d+)/settle',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE id=%d",$id),ARRAY_A);if(!$row)return new WP_Error('not_found','Advance not found.',array('status'=>404));$amount=min(max(0,(float)($r->get_json_params()['amount']??0)),(float)$row['remaining']);$remaining=(float)$row['remaining']-$amount;$wpdb->update(self::table(),array('remaining'=>$remaining,'status'=>$remaining<=0?'settled':'open','updated_at'=>current_time('mysql',true)),array('id'=>$id));MUTQAN_Audit::log('advance_settled','advance',$id,array('amount'=>$amount,'remaining'=>$remaining));return rest_ensure_response(array('id'=>$id,'settled_amount'=>$amount,'remaining'=>$remaining));}));}
}
MUTQAN_Advances::init();