<?php
defined('ABSPATH') || exit;
final class MUTQAN_Commissions {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_commission_rules';}
 public static function ledger(){global $wpdb;return $wpdb->prefix.'mutqan_commission_ledger';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,name varchar(190) NOT NULL,role varchar(50) NOT NULL DEFAULT 'mutqan_technician',rate_type varchar(20) NOT NULL DEFAULT 'percent',rate decimal(8,4) NOT NULL DEFAULT 0,min_amount decimal(14,2) NOT NULL DEFAULT 0,max_amount decimal(14,2) NOT NULL DEFAULT 0,active tinyint(1) NOT NULL DEFAULT 1,conditions longtext NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),KEY role(role),KEY active(active)) $c;");dbDelta("CREATE TABLE ".self::ledger()." (id bigint unsigned NOT NULL AUTO_INCREMENT,order_id bigint unsigned NOT NULL,user_id bigint unsigned NOT NULL,base_amount decimal(14,2) NOT NULL,commission_amount decimal(14,2) NOT NULL,rule_id bigint unsigned NOT NULL DEFAULT 0,status varchar(30) NOT NULL DEFAULT 'pending',created_at datetime NOT NULL,paid_at datetime NULL,PRIMARY KEY(id),KEY order_id(order_id),KEY user_id(user_id)) $c;");}
 public static function calculate($uid,$base){global $wpdb;$role='';$u=get_userdata($uid);if($u&&!empty($u->roles[0]))$role=$u->roles[0];$r=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE role=%s AND active=1 ORDER BY id DESC LIMIT 1",$role),ARRAY_A);if(!$r)return array('amount'=>0,'rule_id'=>0);$v=$r['rate_type']==='fixed'?(float)$r['rate']:(float)$base*(float)$r['rate']/100;$v=max((float)$r['min_amount'],$v);if((float)$r['max_amount']>0)$v=min((float)$r['max_amount'],$v);return array('amount'=>round($v,2),'rule_id'=>(int)$r['id']);}
 private static function manage(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');}
 public static function rest(){register_rest_route('mutqan/v1','/commission-rules',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$d=array('name'=>sanitize_text_field($p['name']??'عمولة الفني'),'role'=>sanitize_key($p['role']??'mutqan_technician'),'rate_type'=>sanitize_key($p['rate_type']??'percent'),'rate'=>(float)($p['rate']??0),'min_amount'=>(float)($p['min_amount']??0),'max_amount'=>(float)($p['max_amount']??0),'active'=>empty($p['active'])?0:1,'conditions'=>wp_json_encode($p['conditions']??array()),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true));$wpdb->insert(self::table(),$d);$id=(int)$wpdb->insert_id;MUTQAN_Audit::log('commission_rule_created','commission_rule',$id,array());return rest_ensure_response(array('id'=>$id)+$d);}});register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/commission',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$o=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".MUTQAN_Orders::table()." WHERE id=%d",$id),ARRAY_A);if(!$o||!(int)$o['technician_id'])return new WP_Error('invalid_order','Assigned technician is required.',array('status'=>400));$base=(float)($r->get_json_params()['base_amount']??0);$x=self::calculate((int)$o['technician_id'],$base);$old=$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::ledger()." WHERE order_id=%d",$id));$d=array('order_id'=>$id,'user_id'=>(int)$o['technician_id'],'base_amount'=>$base,'commission_amount'=>$x['amount'],'rule_id'=>$x['rule_id'],'status'=>'pending','created_at'=>current_time('mysql',true));if($old)$wpdb->update(self::ledger(),$d,array('id'=>(int)$old));else$wpdb->insert(self::ledger(),$d);MUTQAN_Audit::log('order_commission_calculated','order',$id,array('technician_id'=>(int)$o['technician_id'],'commission'=>$x['amount']));return rest_ensure_response($d);}});}
}
MUTQAN_Commissions::init();