<?php
defined('ABSPATH') || exit;
final class MUTQAN_Accounting {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_accounts';}
 public static function ledger(){global $wpdb;return $wpdb->prefix.'mutqan_journal';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,code varchar(40) NOT NULL,name varchar(190) NOT NULL,type varchar(30) NOT NULL,active tinyint(1) NOT NULL DEFAULT 1,created_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY code(code)) $c;");dbDelta("CREATE TABLE ".self::ledger()." (id bigint unsigned NOT NULL AUTO_INCREMENT,account_id bigint unsigned NOT NULL,entry_type varchar(20) NOT NULL,amount decimal(14,2) NOT NULL,reference_type varchar(40) NOT NULL DEFAULT '',reference_id bigint unsigned NOT NULL DEFAULT 0,description text NULL,created_at datetime NOT NULL,PRIMARY KEY(id),KEY account_id(account_id),KEY reference(reference_type,reference_id)) $c;");}
 private static function manage(){return current_user_can('mutqan_manage_settings')||current_user_can('mutqan_manage_operations')||current_user_can('mutqan_view_audit');}
 public static function rest(){register_rest_route('mutqan/v1','/accounting/accounts',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function(){global $wpdb;return rest_ensure_response($wpdb->get_results("SELECT * FROM ".self::table()." ORDER BY code",ARRAY_A));}));register_rest_route('mutqan/v1','/accounting/accounts',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$d=array('code'=>sanitize_text_field($p['code']??''),'name'=>sanitize_text_field($p['name']??''),'type'=>sanitize_key($p['type']??'expense'),'active'=>empty($p['active'])?0:1,'created_at'=>current_time('mysql',true));if(!$d['code']||!$d['name'])return new WP_Error('invalid_account','Code and name are required.',array('status'=>400));$wpdb->insert(self::table(),$d);$id=(int)$wpdb->insert_id;MUTQAN_Audit::log('account_created','account',$id,$d);return rest_ensure_response(array('id'=>$id)+$d);}));register_rest_route('mutqan/v1','/accounting/journal',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$aid=absint($p['account_id']??0);$amt=(float)($p['amount']??0);if(!$aid||$amt<=0)return new WP_Error('invalid_entry','Account and positive amount are required.',array('status'=>400));$wpdb->insert(self::ledger(),array('account_id'=>$aid,'entry_type'=>sanitize_key($p['entry_type']??'debit'),'amount'=>$amt,'reference_type'=>sanitize_key($p['reference_type']??''),'reference_id'=>absint($p['reference_id']??0),'description'=>sanitize_textarea_field($p['description']??''),'created_at'=>current_time('mysql',true)));$id=(int)$wpdb->insert_id;MUTQAN_Audit::log('journal_entry_created','journal',$id,array());return rest_ensure_response(array('id'=>$id,'saved'=>true));}));}
}
MUTQAN_Accounting::init();