<?php
defined('ABSPATH') || exit;
final class MUTQAN_Fleet {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_fleet';}
 public static function stock_table(){global $wpdb;return $wpdb->prefix.'mutqan_vehicle_inventory';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();
  dbDelta("CREATE TABLE ".self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,vehicle_code varchar(80) NOT NULL,name varchar(190) NOT NULL,plate varchar(80) NOT NULL DEFAULT '',technician_id bigint unsigned NOT NULL DEFAULT 0,status varchar(30) NOT NULL DEFAULT 'active',capacity decimal(12,2) NOT NULL DEFAULT 0,notes text NULL,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY vehicle_code(vehicle_code),KEY technician_id(technician_id),KEY status(status)) $c;");
  dbDelta("CREATE TABLE ".self::stock_table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,vehicle_id bigint unsigned NOT NULL,inventory_id bigint unsigned NOT NULL,quantity decimal(12,2) NOT NULL DEFAULT 0,reserved decimal(12,2) NOT NULL DEFAULT 0,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY vehicle_item(vehicle_id,inventory_id),KEY vehicle_id(vehicle_id),KEY inventory_id(inventory_id)) $c;");
 }
 private static function manage(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');}
 public static function rest(){
  register_rest_route('mutqan/v1','/fleet',array('methods'=>'GET','permission_callback'=>function(){return self::manage();},'callback'=>function(){global $wpdb;return rest_ensure_response($wpdb->get_results("SELECT f.*,u.display_name technician_name FROM ".self::table()." f LEFT JOIN {$wpdb->users} u ON u.ID=f.technician_id ORDER BY f.id DESC",ARRAY_A));}));
  register_rest_route('mutqan/v1','/fleet',array('methods'=>'POST','permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$d=array('vehicle_code'=>sanitize_key($p['vehicle_code']??''),'name'=>sanitize_text_field($p['name']??''),'plate'=>sanitize_text_field($p['plate']??''),'technician_id'=>absint($p['technician_id']??0),'status'=>sanitize_key($p['status']??'active'),'capacity'=>max(0,(float)($p['capacity']??0)),'notes'=>sanitize_textarea_field($p['notes']??''),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true));if(!$d['vehicle_code']||!$d['name'])return new WP_Error('invalid_vehicle','vehicle_code and name are required.',array('status'=>400));$ok=$wpdb->replace(self::table(),$d);if(!$ok)return new WP_Error('vehicle_save_failed','تعذر حفظ المركبة.',array('status'=>500));$id=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::table()." WHERE vehicle_code=%s",$d['vehicle_code']));MUTQAN_Audit::log('fleet_vehicle_saved','fleet',$id,array('vehicle_code'=>$d['vehicle_code']));return rest_ensure_response(array('id'=>$id)+$d);}));
  register_rest_route('mutqan/v1','/fleet/(?P<id>\d+)/inventory',array('methods'=>'GET','permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$rows=$wpdb->get_results($wpdb->prepare("SELECT vi.*,i.sku,i.name,i.unit_cost,GREATEST(vi.quantity-vi.reserved,0) available FROM ".self::stock_table()." vi JOIN ".MUTQAN_Inventory::table()." i ON i.id=vi.inventory_id WHERE vi.vehicle_id=%d ORDER BY i.name",$id),ARRAY_A);return rest_ensure_response($rows);}));
  register_rest_route('mutqan/v1','/fleet/(?P<id>\d+)/inventory',array('methods'=>'POST','permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$vehicle=(int)$r['id'];$p=$r->get_json_params();$iid=absint($p['inventory_id']??0);$qty=max(0,(float)($p['quantity']??0));if(!$iid||!$qty)return new WP_Error('invalid_stock','inventory_id and quantity are required.',array('status'=>400));$item=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".MUTQAN_Inventory::table()." WHERE id=%d",$iid),ARRAY_A);if(!$item)return new WP_Error('inventory_not_found','الصنف غير موجود.',array('status'=>404));$existing=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::stock_table()." WHERE vehicle_id=%d AND inventory_id=%d",$vehicle,$iid),ARRAY_A);$new=$existing?(float)$existing['quantity']+$qty:$qty;if($existing)$wpdb->update(self::stock_table(),array('quantity'=>$new,'updated_at'=>current_time('mysql',true)),array('id'=>(int)$existing['id']),array('%f','%s'),array('%d'));else $wpdb->insert(self::stock_table(),array('vehicle_id'=>$vehicle,'inventory_id'=>$iid,'quantity'=>$qty,'reserved'=>0,'updated_at'=>current_time('mysql',true)),array('%d','%d','%f','%d','%s'));MUTQAN_Audit::log('vehicle_stock_added','fleet',$vehicle,array('inventory_id'=>$iid,'quantity'=>$qty));return rest_ensure_response(array('ok'=>true,'vehicle_id'=>$vehicle,'inventory_id'=>$iid,'quantity'=>$new));}));
 }
}
MUTQAN_Fleet::init();
