<?php
defined('ABSPATH') || exit;
final class MUTQAN_Inventory {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_inventory';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, sku varchar(80) NOT NULL, name varchar(190) NOT NULL, warehouse varchar(190) NOT NULL DEFAULT '', quantity decimal(12,2) NOT NULL DEFAULT 0, reserved decimal(12,2) NOT NULL DEFAULT 0, unit_cost decimal(12,2) NOT NULL DEFAULT 0, reorder_level decimal(12,2) NOT NULL DEFAULT 0, active tinyint(1) NOT NULL DEFAULT 1, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY(id),UNIQUE KEY sku(sku),KEY warehouse(warehouse)) $c;");}
 private static function manage(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');}
 public static function rest(){
  register_rest_route('mutqan/v1','/inventory',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function(){global $wpdb;return rest_ensure_response($wpdb->get_results("SELECT *,GREATEST(quantity-reserved,0) available FROM ".self::table()." ORDER BY name ASC",ARRAY_A));}));
  register_rest_route('mutqan/v1','/inventory',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$d=array('sku'=>sanitize_text_field($p['sku']??''),'name'=>sanitize_text_field($p['name']??''),'warehouse'=>sanitize_text_field($p['warehouse']??''),'quantity'=>max(0,(float)($p['quantity']??0)),'reserved'=>max(0,(float)($p['reserved']??0)),'unit_cost'=>max(0,(float)($p['unit_cost']??0)),'reorder_level'=>max(0,(float)($p['reorder_level']??0)),'active'=>empty($p['active'])?0:1,'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true));if($d['sku']===''||$d['name']==='')return new WP_Error('invalid_item','SKU and name are required.',array('status'=>400));$wpdb->replace(self::table(),$d);$id=(int)$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::table()." WHERE sku=%s",$d['sku']));MUTQAN_Audit::log('inventory_item_saved','inventory',$id,array('sku'=>$d['sku']));return rest_ensure_response(array('id'=>$id)+$d);}}); 
  register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/parts',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function($r){return MUTQAN_Orders::can_view((int)$r['id'])&&(current_user_can('mutqan_manage_operations')||current_user_can('mutqan_edit_orders'));},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$items=(array)($r->get_json_params()['items']??array());foreach($items as $item){$iid=absint($item['inventory_id']??0);$qty=max(0,(float)($item['quantity']??0));if(!$iid||!$qty)continue;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE id=%d",$iid),ARRAY_A);if(!$row||((float)$row['quantity']-(float)$row['reserved'])<$qty)return new WP_Error('insufficient_stock','Insufficient stock.',array('status'=>400));$wpdb->update(self::table(),array('reserved'=>(float)$row['reserved']+$qty,'updated_at'=>current_time('mysql',true)),array('id'=>$iid));}MUTQAN_Audit::log('order_parts_reserved','order',$id,array('items'=>$items));return rest_ensure_response(array('order_id'=>$id,'reserved'=>true));}));
 }
}
MUTQAN_Inventory::init();