<?php
defined('ABSPATH') || exit;

final class MUTQAN_Field_Execution {
    public static function init(){ add_action('rest_api_init',array(__CLASS__,'rest')); }
    public static function table(){ global $wpdb; return $wpdb->prefix.'mutqan_field_execution'; }
    public static function install(){
        global $wpdb; require_once ABSPATH.'wp-admin/includes/upgrade.php'; $c=$wpdb->get_charset_collate();
        dbDelta("CREATE TABLE ".self::table()." (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, order_id bigint(20) unsigned NOT NULL, technician_id bigint(20) unsigned NOT NULL, diagnosis longtext NULL, work_report longtext NULL, checklist longtext NULL, parts_used longtext NULL, before_photos longtext NULL, after_photos longtext NULL, customer_confirmation longtext NULL, signature_attachment_id bigint(20) unsigned NOT NULL DEFAULT 0, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY(id), KEY order_id(order_id), KEY technician_id(technician_id)) $c;");
    }
    private static function order($id){ global $wpdb; return $wpdb->get_row($wpdb->prepare("SELECT * FROM ".MUTQAN_Orders::table()." WHERE id=%d",$id),ARRAY_A); }
    private static function can_edit($o){ return $o && (current_user_can('mutqan_manage_operations')||current_user_can('mutqan_edit_orders')||((int)$o['technician_id']===get_current_user_id()&&MUTQAN_Users::technician_can_receive(get_current_user_id())&&in_array($o['status'],array('arrived','working','waiting_customer'),true))); }
    public static function rest(){
        register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/execution',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function($r){return MUTQAN_Orders::can_view((int)$r['id']);},'callback'=>function($r){global $wpdb;$x=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE order_id=%d",(int)$r['id']),ARRAY_A);if(!$x)return rest_ensure_response(array('order_id'=>(int)$r['id']));foreach(array('checklist','parts_used','before_photos','after_photos') as $k)$x[$k]=$x[$k]?json_decode($x[$k],true):array();return rest_ensure_response($x);}));
        register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/execution',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function($r){return self::can_edit(self::order((int)$r['id']));},'callback'=>function($r){$id=(int)$r['id'];$o=self::order($id);if(!$o)return new WP_Error('not_found','Order not found.',array('status'=>404));$p=$r->get_json_params();$d=array('diagnosis'=>sanitize_textarea_field($p['diagnosis']??''),'work_report'=>sanitize_textarea_field($p['work_report']??''),'checklist'=>wp_json_encode($p['checklist']??array()),'parts_used'=>wp_json_encode(array_map('absint',(array)($p['parts_used']??array()))),'before_photos'=>wp_json_encode(array_map('absint',(array)($p['before_photos']??array()))),'after_photos'=>wp_json_encode(array_map('absint',(array)($p['after_photos']??array()))),'customer_confirmation'=>sanitize_textarea_field($p['customer_confirmation']??''),'signature_attachment_id'=>absint($p['signature_attachment_id']??0),'updated_at'=>current_time('mysql',true));global $wpdb;$exists=$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::table()." WHERE order_id=%d",$id));if($exists)$wpdb->update(self::table(),$d,array('id'=>(int)$exists));else{$d['order_id']=$id;$d['technician_id']=(int)$o['technician_id'];$d['created_at']=current_time('mysql',true);$wpdb->insert(self::table(),$d);}MUTQAN_Audit::log('field_execution_saved','order',$id,array('technician_id'=>get_current_user_id()));return rest_ensure_response(array('order_id'=>$id,'saved'=>true));}));
        register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/confirm-completion',array('methods'=>WP_REST_Server::EDITABLE,'permission_callback'=>function($r){return MUTQAN_Orders::can_view((int)$r['id']);},'callback'=>function($r){$id=(int)$r['id'];$o=self::order($id);if(!$o)return new WP_Error('not_found','Order not found.',array('status'=>404));if((int)$o['customer_id']!==get_current_user_id()&&!current_user_can('mutqan_manage_operations'))return new WP_Error('forbidden','Customer confirmation required.',array('status'=>403));global $wpdb;$x=$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::table()." WHERE order_id=%d",$id));if(!$x)return new WP_Error('missing_report','Technician report is required.',array('status'=>400));$p=$r->get_json_params();$wpdb->update(self::table(),array('customer_confirmation'=>sanitize_textarea_field($p['confirmation']??'Confirmed'),'updated_at'=>current_time('mysql',true)),array('order_id'=>$id));$ok=MUTQAN_Orders::transition($id,'completed',get_current_user_id());if(is_wp_error($ok))return $ok;return rest_ensure_response(array('id'=>$id,'status'=>'completed'));}));
    }
}
MUTQAN_Field_Execution::init();
