<?php
defined('ABSPATH') || exit;
final class MUTQAN_Promotions {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_promotions';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, code varchar(80) NOT NULL, name varchar(190) NOT NULL, type varchar(30) NOT NULL DEFAULT 'percent', value decimal(12,2) NOT NULL DEFAULT 0, min_order decimal(12,2) NOT NULL DEFAULT 0, usage_limit int NOT NULL DEFAULT 0, used_count int NOT NULL DEFAULT 0, starts_at datetime NULL, ends_at datetime NULL, active tinyint(1) NOT NULL DEFAULT 1, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY(id),UNIQUE KEY code(code)) $c;");}
 private static function manage(){return current_user_can('mutqan_manage_marketing')||current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');}
 public static function apply($code,$subtotal){global $wpdb;$p=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE code=%s AND active=1",$code),ARRAY_A);if(!$p)return new WP_Error('invalid_coupon','Invalid coupon.');$now=current_time('mysql',true);if(($p['starts_at']&&$now<$p['starts_at'])||($p['ends_at']&&$now>$p['ends_at']))return new WP_Error('expired_coupon','Coupon is not active.');if($p['usage_limit']>0&&$p['used_count']>=$p['usage_limit'])return new WP_Error('coupon_limit','Coupon usage limit reached.');if($subtotal<$p['min_order'])return new WP_Error('minimum_order','Minimum order not reached.');$discount=$p['type']==='fixed'?min($subtotal,(float)$p['value']):min($subtotal,$subtotal*((float)$p['value']/100));return array('promotion_id'=>(int)$p['id'],'discount'=>round($discount,2));}
 public static function rest(){register_rest_route('mutqan/v1','/promotions',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function(){global $wpdb;return rest_ensure_response($wpdb->get_results("SELECT * FROM ".self::table()." ORDER BY id DESC",ARRAY_A));}));register_rest_route('mutqan/v1','/promotions',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$d=array('code'=>sanitize_text_field($p['code']??''),'name'=>sanitize_text_field($p['name']??''),'type'=>sanitize_key($p['type']??'percent'),'value'=>(float)($p['value']??0),'min_order'=>(float)($p['min_order']??0),'usage_limit'=>(int)($p['usage_limit']??0),'starts_at'=>!empty($p['starts_at'])?sanitize_text_field($p['starts_at']):null,'ends_at'=>!empty($p['ends_at'])?sanitize_text_field($p['ends_at']):null,'active'=>empty($p['active'])?0:1,'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true));if($d['code']===''||$d['name']==='')return new WP_Error('invalid_promotion','Code and name are required.',array('status'=>400));$wpdb->insert(self::table(),$d);$id=(int)$wpdb->insert_id;MUTQAN_Audit::log('promotion_created','promotion',$id,array());return rest_ensure_response(array('id'=>$id)+$d);}});}
}
MUTQAN_Promotions::init();