<?php
defined('ABSPATH') || exit;
final class MUTQAN_Ratings {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_ratings';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, order_id bigint(20) unsigned NOT NULL, customer_id bigint(20) unsigned NOT NULL, rating tinyint unsigned NOT NULL, comment text NULL, created_at datetime NOT NULL, PRIMARY KEY(id),UNIQUE KEY order_customer(order_id,customer_id),KEY customer_id(customer_id)) $c;");}
 public static function rest(){register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/rating',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function($r){return MUTQAN_Orders::can_view((int)$r['id']);},'callback'=>function($r){global $wpdb;return rest_ensure_response($wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE order_id=%d",(int)$r['id']),ARRAY_A));}));
 register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/rating',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function($r){$o=MUTQAN_Orders::can_view((int)$r['id']);return $o&&get_current_user_id()>0;},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$o=$wpdb->get_row($wpdb->prepare("SELECT customer_id,status FROM ".MUTQAN_Orders::table()." WHERE id=%d",$id),ARRAY_A);if(!$o||$o['status']!=='completed'||(int)$o['customer_id']!==get_current_user_id())return new WP_Error('forbidden','Only the customer can rate a completed order.',array('status'=>403));$p=$r->get_json_params();$rating=max(1,min(5,(int)($p['rating']??0)));if(!$rating)return new WP_Error('invalid_rating','Rating must be 1-5.',array('status'=>400));$d=array('order_id'=>$id,'customer_id'=>get_current_user_id(),'rating'=>$rating,'comment'=>sanitize_textarea_field($p['comment']??''),'created_at'=>current_time('mysql',true));$wpdb->replace(self::table(),$d);MUTQAN_Audit::log('service_rated','order',$id,array('rating'=>$rating));return rest_ensure_response(array('order_id'=>$id,'rating'=>$rating));}));}
}
MUTQAN_Ratings::init();
