<?php
defined('ABSPATH') || exit;
final class MUTQAN_Pricing {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_price_rules';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, service_id bigint(20) unsigned NOT NULL DEFAULT 0, name varchar(190) NOT NULL, rule_type varchar(30) NOT NULL DEFAULT 'fixed', amount decimal(12,2) NOT NULL DEFAULT 0, active tinyint(1) NOT NULL DEFAULT 1, priority int NOT NULL DEFAULT 0, conditions longtext NULL, created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY(id),KEY service_id(service_id),KEY active(active)) $c;");}
 private static function manage(){return current_user_can('mutqan_manage_pricing')||current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');}
 public static function calculate($service_id,$base=0){global $wpdb;$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".self::table()." WHERE service_id IN (0,%d) AND active=1 ORDER BY priority DESC,id ASC",$service_id),ARRAY_A);$total=(float)$base;foreach($rows as $r){$a=(float)$r['amount'];if($r['rule_type']==='fixed')$total+=$a;elseif($r['rule_type']==='percent')$total+=$total*$a/100;elseif($r['rule_type']==='discount_percent')$total-=$total*$a/100;elseif($r['rule_type']==='discount_fixed')$total-=$a;}return max(0,round($total,2));}
 public static function rest(){register_rest_route('mutqan/v1','/pricing/rules',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function(){global $wpdb;return rest_ensure_response($wpdb->get_results("SELECT * FROM ".self::table()." ORDER BY priority DESC,id DESC",ARRAY_A));}));register_rest_route('mutqan/v1','/pricing/rules',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return self::manage();},'callback'=>function($r){global $wpdb;$p=$r->get_json_params();$type=sanitize_key($p['rule_type']??'fixed');if(!in_array($type,array('fixed','percent','discount_percent','discount_fixed'),true))return new WP_Error('invalid_rule','Invalid pricing rule.',array('status'=>400));$d=array('service_id'=>absint($p['service_id']??0),'name'=>sanitize_text_field($p['name']??'قاعدة سعر'),'rule_type'=>$type,'amount'=>(float)($p['amount']??0),'active'=>empty($p['active'])?0:1,'priority'=>(int)($p['priority']??0),'conditions'=>wp_json_encode($p['conditions']??array()),'created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true));$wpdb->insert(self::table(),$d);$id=(int)$wpdb->insert_id;MUTQAN_Audit::log('pricing_rule_created','pricing_rule',$id,array());return rest_ensure_response(array('id'=>$id)+$d);}));}
}
MUTQAN_Pricing::init();