<?php
defined('ABSPATH') || exit;
final class MUTQAN_Quality {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_quality_checks';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,order_id bigint unsigned NOT NULL,technician_id bigint unsigned NOT NULL,score tinyint unsigned NOT NULL DEFAULT 0,checklist longtext NULL,notes longtext NULL,status varchar(30) NOT NULL DEFAULT 'pending',reviewer_id bigint unsigned NOT NULL DEFAULT 0,created_at datetime NOT NULL,updated_at datetime NOT NULL,PRIMARY KEY(id),UNIQUE KEY order_id(order_id),KEY technician_id(technician_id),KEY status(status)) $c;");}
 public static function rest(){register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/quality',array('methods'=>'GET','permission_callback'=>function($r){return MUTQAN_Orders::can_view((int)$r['id']);},'callback'=>function($r){global $wpdb;$x=$wpdb->get_row($wpdb->prepare("SELECT * FROM ".self::table()." WHERE order_id=%d",(int)$r['id']),ARRAY_A);if($x)$x['checklist']=$x['checklist']?json_decode($x['checklist'],true):array();return rest_ensure_response($x);}));
 register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/quality',array('methods'=>'POST','permission_callback'=>function(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_edit_orders');},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$o=$wpdb->get_row($wpdb->prepare("SELECT technician_id FROM ".MUTQAN_Orders::table()." WHERE id=%d",$id),ARRAY_A);if(!$o)return new WP_Error('not_found','Order not found.',array('status'=>404));$p=$r->get_json_params();$score=max(0,min(100,(int)($p['score']??0)));$status=in_array(($p['status']??'approved'),array('pending','approved','rework','rejected'),true)?sanitize_key($p['status']):'approved';$d=array('order_id'=>$id,'technician_id'=>(int)$o['technician_id'],'score'=>$score,'checklist'=>wp_json_encode($p['checklist']??array()),'notes'=>sanitize_textarea_field($p['notes']??''),'status'=>$status,'reviewer_id'=>get_current_user_id(),'updated_at'=>current_time('mysql',true));$exists=$wpdb->get_var($wpdb->prepare("SELECT id FROM ".self::table()." WHERE order_id=%d",$id));if($exists)$wpdb->update(self::table(),$d,array('id'=>(int)$exists));else{$d['created_at']=current_time('mysql',true);$wpdb->insert(self::table(),$d);}$qid=$exists?(int)$exists:(int)$wpdb->insert_id;MUTQAN_Audit::log('quality_check_saved','order',$id,array('quality_id'=>$qid,'score'=>$score,'status'=>$status));
  if(class_exists('MUTQAN_CRM')){
   $customer=(int)$wpdb->get_var($wpdb->prepare("SELECT customer_id FROM ".MUTQAN_Orders::table()." WHERE id=%d",$id));
   if($customer) MUTQAN_CRM::add($customer,$id,'quality','مراجعة الجودة','نتيجة الجودة: '.$score.'/100 — '.$status,'system');
  }return rest_ensure_response(array('id'=>$qid,'order_id'=>$id,'score'=>$score,'status'=>$status));}));
 }
}
MUTQAN_Quality::init();