<?php
defined('ABSPATH') || exit;
final class MUTQAN_Warranty {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_warranties';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint(20) unsigned NOT NULL AUTO_INCREMENT, order_id bigint(20) unsigned NOT NULL, customer_id bigint(20) unsigned NOT NULL, title varchar(190) NOT NULL, details longtext NULL, starts_at datetime NOT NULL, ends_at datetime NULL, status varchar(30) NOT NULL DEFAULT 'active', created_at datetime NOT NULL, updated_at datetime NOT NULL, PRIMARY KEY(id),KEY order_id(order_id),KEY customer_id(customer_id)) $c;");}
 public static function rest(){register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/warranty',array('methods'=>WP_REST_Server::READABLE,'permission_callback'=>function($r){return MUTQAN_Orders::can_view((int)$r['id']);},'callback'=>function($r){global $wpdb;$x=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".self::table()." WHERE order_id=%d ORDER BY id DESC",(int)$r['id']),ARRAY_A);return rest_ensure_response($x);}));
 register_rest_route('mutqan/v1','/orders/(?P<id>\d+)/warranty',array('methods'=>WP_REST_Server::CREATABLE,'permission_callback'=>function(){return current_user_can('mutqan_manage_operations')||current_user_can('mutqan_manage_settings');},'callback'=>function($r){global $wpdb;$id=(int)$r['id'];$o=$wpdb->get_row($wpdb->prepare("SELECT customer_id FROM ".MUTQAN_Orders::table()." WHERE id=%d",$id),ARRAY_A);if(!$o)return new WP_Error('not_found','Order not found.',array('status'=>404));$p=$r->get_json_params();$start=!empty($p['starts_at'])?sanitize_text_field($p['starts_at']):current_time('mysql',true);$d=array('order_id'=>$id,'customer_id'=>(int)$o['customer_id'],'title'=>sanitize_text_field($p['title']??'ضمان الخدمة'),'details'=>sanitize_textarea_field($p['details']??''),'starts_at'=>$start,'ends_at'=>!empty($p['ends_at'])?sanitize_text_field($p['ends_at']):null,'status'=>'active','created_at'=>current_time('mysql',true),'updated_at'=>current_time('mysql',true));$wpdb->insert(self::table(),$d);$wid=(int)$wpdb->insert_id;MUTQAN_Audit::log('warranty_created','order',$id,array('warranty_id'=>$wid));
  if(class_exists('MUTQAN_CRM')) MUTQAN_CRM::add((int)$o['customer_id'],$id,'warranty','إنشاء ضمان','تم إنشاء ضمان للخدمة.','system');return rest_ensure_response(array('id'=>$wid,'order_id'=>$id,'status'=>'active'));}));}
}
MUTQAN_Warranty::init();
