<?php
defined('ABSPATH') || exit;
final class MUTQAN_AI {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));add_action('rest_api_init',array(__CLASS__,'public_rest'));add_action('admin_init',array(__CLASS__,'settings'));}
 public static function settings(){add_options_page('MUTQAN AI','MUTQAN AI','manage_options','mutqan-ai',function(){echo '<div class="wrap" dir="rtl"><h1>MUTQAN AI</h1><form method="post" action="options.php">';settings_fields('mutqan_ai');do_settings_sections('mutqan_ai');submit_button('حفظ إعدادات Gemini');echo '</form></div>';});register_setting('mutqan_ai','mutqan_gemini_api_key',array('sanitize_callback'=>'sanitize_text_field'));register_setting('mutqan_ai','mutqan_gemini_model',array('sanitize_callback'=>'sanitize_text_field'));add_settings_section('mq_ai','Gemini AI',function(){echo '<p>مفتاح Gemini محفوظ في إعدادات WordPress ولا يظهر للواجهة.</p>';},'mutqan_ai');add_settings_field('mutqan_gemini_api_key','Gemini API Key',function(){echo '<input type="password" name="mutqan_gemini_api_key" value="" class="regular-text" autocomplete="off"><p class="description">اتركه فارغاً لعدم تغييره.</p>';},'mutqan_ai','mq_ai');add_settings_field('mutqan_gemini_model','Gemini Model',function(){echo '<input name="mutqan_gemini_model" value="'.esc_attr(get_option('mutqan_gemini_model','gemini-2.5-flash')).'" class="regular-text">';},'mutqan_ai','mq_ai');}
 private static function allowed(){return is_user_logged_in() && (current_user_can('mutqan_manage_ai')||current_user_can('mutqan_view_orders')||current_user_can('mutqan_view_own_orders'));}
 private static function context(){global $wpdb;$uid=get_current_user_id();$role=wp_get_current_user()->roles;$orders=$wpdb->get_results($wpdb->prepare("SELECT id,status,type,priority,lat,lng,payload FROM ".MUTQAN_Operations::table()." WHERE customer_id=%d OR technician_id=%d ORDER BY id DESC LIMIT 10",$uid,$uid),ARRAY_A);foreach($orders as &$o){$o['payload']=$o['payload']?json_decode($o['payload'],true):array();}return array('user_id'=>$uid,'roles'=>$role,'orders'=>$orders);}
 public static function public_rest(){register_rest_route('mutqan/v1','/public/ai/chat',array('methods'=>'POST','permission_callback'=>'__return_true','callback'=>function($r){$ip=sanitize_text_field($_SERVER['REMOTE_ADDR']??'unknown');$k='mq_public_ai_'.md5($ip);$n=(int)get_transient($k);if($n>=10)return new WP_Error('rate_limited','تم تجاوز حد الاستخدام، حاول لاحقاً.',array('status'=>429));set_transient($k,$n+1,HOUR_IN_SECONDS);$p=$r->get_json_params();$msg=sanitize_textarea_field($p['message']??'');if($msg==='')return new WP_Error('empty_message','الرسالة مطلوبة.',array('status'=>400));$key=get_option('mutqan_gemini_api_key','');if(!$key)return new WP_Error('ai_not_configured','Gemini AI غير مُعد بعد.',array('status'=>503));$model=sanitize_text_field(get_option('mutqan_gemini_model','gemini-2.5-flash'));$url='https://generativelanguage.googleapis.com/v1beta/models/'.rawurlencode($model).':generateContent?key='.rawurlencode($key);$res=wp_remote_post($url,array('timeout'=>30,'headers'=>array('Content-Type'=>'application/json'),'body'=>wp_json_encode(array('systemInstruction'=>array('parts'=>array(array('text'=>'أنت مساعد خدمة عملاء لمُتقِن. أجب بالعربية، اشرح الخدمات، اجمع بيانات طلب الخدمة عند الحاجة، ولا تطلب أو تكشف كلمات المرور أو المفاتيح. أنت تتحدث مع زائر ولا تملك بياناته الخاصة.'))),'contents'=>array(array('role'=>'user','parts'=>array(array('text'=>$msg))))))));if(is_wp_error($res))return new WP_Error('ai_request_failed','تعذر الاتصال بمزود الذكاء الاصطناعي.',array('status'=>502));$b=json_decode(wp_remote_retrieve_body($res),true);$t=$b['candidates'][0]['content']['parts'][0]['text']??'لم يصل رد.';return rest_ensure_response(array('reply'=>$t,'model'=>$model));}));}
 public static function rest(){register_rest_route('mutqan/v1','/ai/chat',array('methods'=>'POST','permission_callback'=>array(__CLASS__,'allowed'),'callback'=>function($r){$key=get_option('mutqan_gemini_api_key','');if(!$key)return new WP_Error('ai_not_configured','Gemini AI غير مُعد بعد.',array('status'=>503));$p=$r->get_json_params();$message=sanitize_textarea_field($p['message']??'');if($message==='')return new WP_Error('empty_message','الرسالة مطلوبة.',array('status'=>400));$ctx=self::context();$system='أنت مساعد مُتقِن. أجب بالعربية بوضوح. لا تكشف كلمات المرور أو المفاتيح أو البيانات السرية. لا تنفذ إجراءً حساساً من هذه المحادثة؛ اقترح الإجراء فقط ما لم يكن هناك endpoint مصرح به. التزم بصلاحيات المستخدم. بيانات المستخدم الحالية: '.wp_json_encode($ctx,JSON_UNESCAPED_UNICODE);$model=sanitize_text_field(get_option('mutqan_gemini_model','gemini-2.5-flash'));$url='https://generativelanguage.googleapis.com/v1beta/models/'.rawurlencode($model).':generateContent?key='.rawurlencode($key);$res=wp_remote_post($url,array('timeout'=>30,'headers'=>array('Content-Type'=>'application/json'),'body'=>wp_json_encode(array('systemInstruction'=>array('parts'=>array(array('text'=>$system))),'contents'=>array(array('role'=>'user','parts'=>array(array('text'=>$message))))))));if(is_wp_error($res))return new WP_Error('ai_request_failed','تعذر الاتصال بمزود الذكاء الاصطناعي.',array('status'=>502));$code=wp_remote_retrieve_response_code($res);$body=json_decode(wp_remote_retrieve_body($res),true);if($code<200||$code>=300)return new WP_Error('ai_provider_error','تعذر تنفيذ طلب Gemini.',array('status'=>502,'provider_status'=>$code));$text=$body['candidates'][0]['content']['parts'][0]['text']??'لم يصل رد من Gemini.';MUTQAN_Audit::log('ai_chat','user',get_current_user_id(),array('message_length'=>strlen($message)));return rest_ensure_response(array('reply'=>$text,'model'=>$model));}));}
}
MUTQAN_AI::init();
