<?php
defined('ABSPATH') || exit;
final class MUTQAN_Notifications {
 public static function init(){add_action('rest_api_init',array(__CLASS__,'rest'));foreach(array('order_created','order_assigned','order_status_changed','message_sent') as $e)MUTQAN_Events::listen($e,array(__CLASS__,'event'),30);}
 public static function table(){global $wpdb;return $wpdb->prefix.'mutqan_notifications';}
 public static function install(){global $wpdb;require_once ABSPATH.'wp-admin/includes/upgrade.php';$c=$wpdb->get_charset_collate();dbDelta("CREATE TABLE ".self::table()." (id bigint unsigned NOT NULL AUTO_INCREMENT,user_id bigint unsigned NOT NULL,type varchar(40) NOT NULL,title varchar(190) NOT NULL,body text NULL,reference_id bigint unsigned NOT NULL DEFAULT 0,is_read tinyint(1) NOT NULL DEFAULT 0,created_at datetime NOT NULL,read_at datetime NULL,PRIMARY KEY(id),KEY user_read(user_id,is_read),KEY created_at(created_at)) $c;");}
 public static function push($uid,$type,$title,$body='',$ref=0){if(!$uid)return;global $wpdb;$wpdb->insert(self::table(),array('user_id'=>(int)$uid,'type'=>sanitize_key($type),'title'=>sanitize_text_field($title),'body'=>sanitize_textarea_field($body),'reference_id'=>absint($ref),'created_at'=>current_time('mysql',true)),array('%d','%s','%s','%s','%d','%s'));}
 public static function event($p){global $wpdb;$id=absint($p['order_id']??0);if(!$id)return;$o=$wpdb->get_row($wpdb->prepare("SELECT customer_id,technician_id,status FROM ".MUTQAN_Operations::table()." WHERE id=%d",$id),ARRAY_A);if(!$o)return;$event=current_filter();$title='تحديث الطلب #'.$id;$body='تم تحديث الطلب.';if($event==='order_created'){$title='طلب خدمة جديد #'.$id;$body='تم استلام طلبك وبدء المعالجة.';}elseif($event==='order_assigned'){$title='تم إسناد الطلب #'.$id;$body='تم إسناد الطلب إلى فني.';}elseif($event==='order_status_changed'){$body='الحالة الجديدة: '.sanitize_text_field($p['to']??$o['status']);}elseif($event==='message_sent'){$title='رسالة جديدة في الطلب #'.$id;$body='لديك رسالة جديدة.';}self::push((int)$o['customer_id'],'order',$title,$body,$id);if((int)$o['technician_id'])self::push((int)$o['technician_id'],'order',$title,$body,$id);}
 public static function rest(){register_rest_route('mutqan/v1','/notifications',array('methods'=>'GET','permission_callback'=>function(){return is_user_logged_in();},'callback'=>function(){global $wpdb;$uid=get_current_user_id();$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM ".self::table()." WHERE user_id=%d ORDER BY id DESC LIMIT 50",$uid),ARRAY_A);return rest_ensure_response($rows);}));
 register_rest_route('mutqan/v1','/notifications/(?P<id>\d+)/read',array('methods'=>'POST','permission_callback'=>function($r){return is_user_logged_in();},'callback'=>function($r){global $wpdb;$wpdb->update(self::table(),array('is_read'=>1,'read_at'=>current_time('mysql',true)),array('id'=>(int)$r['id'],'user_id'=>get_current_user_id()),array('%d','%s'),array('%d','%d'));return rest_ensure_response(array('ok'=>true));}));}
}
MUTQAN_Notifications::init();
